checks:
  php:
    code_rating: true
    duplication: true
filter:
  paths: ["src/*"]
  excluded_paths:
    - vendor/*
    - drupal/*
tools:
  php_analyzer: true
  php_changetracking: true
  php_mess_detector: true
  php_code_sniffer:
    config:
      standard: Drupal,DrupalPractice
